CREATE OR REPLACE TABLE `fabled-web-509921-g9.raw.customers` AS SELECT *, TIMESTAMP '2026-09-23 00:00:00+00' updated_at, 'demo_full' id_carga, 'seed_sintetico' origem, CURRENT_TIMESTAMP() ingerido_em FROM UNNEST([STRUCT(1 AS customer_id, 'Mercado Horizonte' AS customer_name, 'RS' AS state, 'Varejo' AS segment),STRUCT(2 AS customer_id, 'Casa Norte' AS customer_name, 'SC' AS state, 'Varejo' AS segment),STRUCT(3 AS customer_id, 'Distribuidora Serra' AS customer_name, 'PR' AS state, 'Distribuidor' AS segment),STRUCT(4 AS customer_id, 'Grupo Central' AS customer_name, 'SP' AS state, 'Key Account' AS segment),STRUCT(5 AS customer_id, 'Rede Avenida' AS customer_name, 'RS' AS state, 'Key Account' AS segment),STRUCT(6 AS customer_id, 'Comercial Aurora' AS customer_name, 'SC' AS state, 'Varejo' AS segment),STRUCT(7 AS customer_id, 'Atacado Sul' AS customer_name, 'PR' AS state, 'Distribuidor' AS segment),STRUCT(8 AS customer_id, 'Lojas Imperial' AS customer_name, 'SP' AS state, 'Varejo' AS segment),STRUCT(9 AS customer_id, 'Grupo Estação' AS customer_name, 'RJ' AS state, 'Key Account' AS segment),STRUCT(10 AS customer_id, 'Comercial Porto' AS customer_name, 'RS' AS state, 'Varejo' AS segment),STRUCT(11 AS customer_id, 'Rede Ponto Certo' AS customer_name, 'SC' AS state, 'Varejo' AS segment),STRUCT(12 AS customer_id, 'Distribuidora Vale' AS customer_name, 'PR' AS state, 'Distribuidor' AS segment),STRUCT(13 AS customer_id, 'Grupo Atlântico' AS customer_name, 'SP' AS state, 'Key Account' AS segment),STRUCT(14 AS customer_id, 'Casa Oliveira' AS customer_name, 'RS' AS state, 'Varejo' AS segment),STRUCT(15 AS customer_id, 'Rede União' AS customer_name, 'SC' AS state, 'Varejo' AS segment),STRUCT(16 AS customer_id, 'Comercial Vitória' AS customer_name, 'PR' AS state, 'Varejo' AS segment),STRUCT(17 AS customer_id, 'Atacado Regional' AS customer_name, 'SP' AS state, 'Distribuidor' AS segment),STRUCT(18 AS customer_id, 'Rede Primavera' AS customer_name, 'RS' AS state, 'Varejo' AS segment),STRUCT(19 AS customer_id, 'Grupo Alameda' AS customer_name, 'SC' AS state, 'Key Account' AS segment),STRUCT(20 AS customer_id, 'Comercial Planalto' AS customer_name, 'PR' AS state, 'Varejo' AS segment)]);

CREATE OR REPLACE TABLE `fabled-web-509921-g9.raw.products` AS SELECT *, 'Calcados' category, TIMESTAMP '2026-09-23 00:00:00+00' updated_at, 'demo_full' id_carga, 'seed_sintetico' origem, CURRENT_TIMESTAMP() ingerido_em FROM UNNEST([STRUCT(101 AS product_id, 'Linha Urban' AS product_name, NUMERIC '189.90' AS list_price, NUMERIC '104.40' AS unit_cost),STRUCT(102 AS product_id, 'Linha Classic' AS product_name, NUMERIC '229.90' AS list_price, NUMERIC '132.20' AS unit_cost),STRUCT(103 AS product_id, 'Linha Outdoor' AS product_name, NUMERIC '279.90' AS list_price, NUMERIC '161.50' AS unit_cost),STRUCT(104 AS product_id, 'Linha Comfort' AS product_name, NUMERIC '159.90' AS list_price, NUMERIC '92.70' AS unit_cost),STRUCT(105 AS product_id, 'Linha Premium' AS product_name, NUMERIC '329.90' AS list_price, NUMERIC '213.60' AS unit_cost)]);

CREATE OR REPLACE TABLE `fabled-web-509921-g9.raw.salespeople` AS SELECT *, TIMESTAMP '2026-09-23 00:00:00+00' updated_at, 'demo_full' id_carga, 'seed_sintetico' origem, CURRENT_TIMESTAMP() ingerido_em FROM UNNEST([STRUCT(1 AS salesperson_id, 'Ana Martins' AS salesperson_name, 'Sul' AS region),STRUCT(2 AS salesperson_id, 'Carlos Lima' AS salesperson_name, 'Sudeste' AS region),STRUCT(3 AS salesperson_id, 'Marina Souza' AS salesperson_name, 'Sul' AS region),STRUCT(4 AS salesperson_id, 'Rafael Costa' AS salesperson_name, 'Sudeste' AS region)]);

CREATE OR REPLACE TABLE `fabled-web-509921-g9.raw.orders` AS WITH base AS (SELECT 10000+g order_id, DATE_ADD(DATE '2025-04-01', INTERVAL MOD(g*7,545) DAY) sale_date, MOD(g*7,20)+1 customer_id,101+MOD(g*3,5) product_id,MOD(g*5,4)+1 salesperson_id,3+MOD(g*11,28) quantity, CAST(150+MOD(g*13,180)+(MOD(g,5)-2)*3.5 AS NUMERIC) unit_price,IF(MOD(g,37)=0,'cancelled','invoiced') status FROM UNNEST(GENERATE_ARRAY(1,900)) g) SELECT *, TIMESTAMP_ADD(TIMESTAMP(sale_date),INTERVAL 20 HOUR) updated_at,'demo_full' id_carga,'seed_sintetico' origem,CURRENT_TIMESTAMP() ingerido_em FROM base WHERE NOT(customer_id IN (16,17,18) AND sale_date>=DATE '2026-05-01') AND NOT(customer_id=19 AND sale_date BETWEEN DATE '2025-11-01' AND DATE '2026-04-30');

CREATE OR REPLACE TABLE `fabled-web-509921-g9.raw.metas` AS SELECT DATE_ADD(DATE '2025-04-01',INTERVAL i MONTH) mes_referencia, id_vendedor, CAST(115000+i*2500+id_vendedor*7000 AS NUMERIC) valor_meta,'demo_full' id_carga,'api_fixture_sintetica' origem,CURRENT_TIMESTAMP() ingerido_em FROM UNNEST(GENERATE_ARRAY(0,17)) i CROSS JOIN UNNEST([1,2,3,4]) id_vendedor;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.raw.previsoes` AS SELECT DATE_SUB(DATE_ADD(DATE '2025-07-01',INTERVAL i MONTH), INTERVAL DIV(horizonte_dias,30) MONTH) data_previsao, DATE_ADD(DATE '2025-07-01',INTERVAL i MONTH) mes_referencia,horizonte_dias,CAST(510000+i*9500 AS NUMERIC)*(1+CAST(MOD(i+horizonte_dias,7)-3 AS NUMERIC)/100) valor_previsto,'demo_full' id_carga,'api_fixture_sintetica' origem,CURRENT_TIMESTAMP() ingerido_em FROM UNNEST(GENERATE_ARRAY(0,14)) i CROSS JOIN UNNEST([30,60,120]) horizonte_dias;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.staging.customers` AS SELECT * EXCEPT(id_carga,origem,ingerido_em) FROM `fabled-web-509921-g9.raw.customers` QUALIFY ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY updated_at DESC,ingerido_em DESC)=1;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.staging.products` AS SELECT * EXCEPT(id_carga,origem,ingerido_em) FROM `fabled-web-509921-g9.raw.products` QUALIFY ROW_NUMBER() OVER(PARTITION BY product_id ORDER BY updated_at DESC,ingerido_em DESC)=1;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.staging.salespeople` AS SELECT * EXCEPT(id_carga,origem,ingerido_em) FROM `fabled-web-509921-g9.raw.salespeople` QUALIFY ROW_NUMBER() OVER(PARTITION BY salesperson_id ORDER BY updated_at DESC,ingerido_em DESC)=1;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.staging.orders` AS SELECT * EXCEPT(id_carga,origem,ingerido_em) FROM `fabled-web-509921-g9.raw.orders` QUALIFY ROW_NUMBER() OVER(PARTITION BY order_id ORDER BY updated_at DESC,ingerido_em DESC)=1;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.staging.metas` AS SELECT * EXCEPT(id_carga,origem,ingerido_em) FROM `fabled-web-509921-g9.raw.metas` QUALIFY ROW_NUMBER() OVER(PARTITION BY mes_referencia,id_vendedor ORDER BY ingerido_em DESC)=1;

CREATE OR REPLACE TABLE `fabled-web-509921-g9.staging.previsoes` AS SELECT * EXCEPT(id_carga,origem,ingerido_em) FROM `fabled-web-509921-g9.raw.previsoes` QUALIFY ROW_NUMBER() OVER(PARTITION BY data_previsao,mes_referencia,horizonte_dias ORDER BY ingerido_em DESC)=1;

ASSERT (SELECT COUNT(*)=COUNT(DISTINCT order_id) AND COUNTIF(order_id IS NULL OR quantity<=0 OR unit_price<0)=0 FROM `fabled-web-509921-g9.staging.orders`) AS 'Chaves, duplicidade, quantidade e preço';
ASSERT (SELECT COUNT(*)=0 FROM `fabled-web-509921-g9.staging.orders` o LEFT JOIN `fabled-web-509921-g9.staging.customers` c USING(customer_id) LEFT JOIN `fabled-web-509921-g9.staging.products` p USING(product_id) LEFT JOIN `fabled-web-509921-g9.staging.salespeople` s USING(salesperson_id) WHERE c.customer_id IS NULL OR p.product_id IS NULL OR s.salesperson_id IS NULL) AS 'Integridade referencial';
CREATE OR REPLACE TABLE `fabled-web-509921-g9.dm.dim_clientes` AS SELECT customer_id id_cliente,customer_name nome_cliente,state uf,segment segmento,updated_at atualizado_em FROM `fabled-web-509921-g9.staging.customers`;
CREATE OR REPLACE TABLE `fabled-web-509921-g9.dm.dim_produtos` AS SELECT product_id id_produto,product_name nome_produto,category categoria,list_price preco_lista,unit_cost custo_unitario,updated_at atualizado_em FROM `fabled-web-509921-g9.staging.products`;
CREATE OR REPLACE TABLE `fabled-web-509921-g9.dm.dim_vendedores` AS SELECT salesperson_id id_vendedor,salesperson_name nome_vendedor,region regiao,updated_at atualizado_em FROM `fabled-web-509921-g9.staging.salespeople`;
CREATE OR REPLACE TABLE `fabled-web-509921-g9.dm.dim_calendario` AS SELECT data,EXTRACT(YEAR FROM data) ano,EXTRACT(MONTH FROM data) mes,EXTRACT(DAY FROM data) dia,EXTRACT(QUARTER FROM data) trimestre,FORMAT_DATE('%Y-%m',data) ano_mes,FORMAT_DATE('%B',data) nome_mes,EXTRACT(DAYOFWEEK FROM data) dia_semana,EXTRACT(DAYOFWEEK FROM data) NOT IN (1,7) dia_util FROM UNNEST(GENERATE_DATE_ARRAY(DATE '2025-01-01',DATE '2028-12-31')) data;
CREATE OR REPLACE TABLE `fabled-web-509921-g9.comercial.fato_lancamento_vendas` AS SELECT o.order_id id_lancamento,o.sale_date data_venda,o.customer_id id_cliente,o.product_id id_produto,o.salesperson_id id_vendedor,o.quantity quantidade,o.unit_price valor_unitario,p.unit_cost custo_unitario,o.quantity*o.unit_price valor_faturamento,o.quantity*p.unit_cost valor_custo,o.quantity*(o.unit_price-p.unit_cost) valor_margem_bruta,SAFE_DIVIDE(o.unit_price-p.unit_cost,o.unit_price) percentual_margem_bruta,o.status,o.updated_at atualizado_em FROM `fabled-web-509921-g9.staging.orders` o LEFT JOIN `fabled-web-509921-g9.staging.products` p USING(product_id);
CREATE OR REPLACE TABLE `fabled-web-509921-g9.comercial.fato_metas` AS SELECT * FROM `fabled-web-509921-g9.staging.metas`;
CREATE OR REPLACE TABLE `fabled-web-509921-g9.comercial.fato_previsao_faturamento` AS SELECT * FROM `fabled-web-509921-g9.staging.previsoes`;
SELECT COUNT(*) lancamentos,COUNTIF(status='invoiced') lancamentos_faturados, SUM(IF(status='invoiced',valor_faturamento,0)) faturamento,SUM(IF(status='invoiced',valor_margem_bruta,0)) margem_bruta,MIN(data_venda) primeira_venda,MAX(data_venda) ultima_venda FROM `fabled-web-509921-g9.comercial.fato_lancamento_vendas`;